### PR TITLE
Use AuthenticationException instead of \Exception

### PR DESCRIPTION
**Pull request by alinalexandru**
AuthenticationException is needed in order to call other listener

### CODE REVIEW

**Comment by ChadSikorra** [comment]
Interesting. I will look at this later tonight to verify. Shouldn't the typehint of `\Exception` allow the AuthenticationException anyway?

**Comment by alinalexandru** [comment]
if you have a class that accepts `AuthenticationException`, you can not pass `\Exception`.
I want to call `https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Event/AuthenticationFailureEvent.php` from the `ldap_tools_bundle.guard.login.failure`

**Comment by ChadSikorra** [comment]
Ah, ok. Now that I look at it this makes sense. Thanks for taking the time to submit this!

**Comment by alinalexandru** [comment]
Can you make another release please?

**Comment by ChadSikorra** [comment]
I have a few other things I want to do first. I want to add CSRF support to the Guard at a minimum. It will probably be another week or so before I tag a new release.

**Comment by alinalexandru** [comment]
Do you need any help?

**Pull request merged**
